import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ramen.glb')
  const ref = useRef()
  const [clicked, click] = useState(false)
  return (
    <group {...props} dispose={null} scale={clicked ? 1.5 : 1} onClick={(e) => console.log('click')}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wood_Props_0.geometry}
        material={materials.Props}
      />
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.stickholder_Props_0.geometry}
        material={materials.Props}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chopsticks_Props_0.geometry}
        material={materials.Props}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_Props_0.geometry}
        material={materials.Props}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spoon_Props_0.geometry}
        material={materials.Props}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spoon_bowl_Added_props_0.geometry}
        material={materials.Added_props}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Broth_broth_0.geometry}
        material={materials.broth}
        position={[1.368, 0.03, 1.6]}
        rotation={[0, -0.087, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.egg_1_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.egg_2_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Noodles_noodles_0.geometry}
        material={materials.noodles}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bowl_Props_0.geometry}
        material={materials.Props}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.banboo_shoot_4_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.banboo_shoot_2_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.banboo_shoot_1_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_2_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_1_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Seaweed2_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Seaweed_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.banboo_shoot_3_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_7_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_8_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_3_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_2_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_15_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_14_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_16_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_1_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_13_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_11_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_17_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_9_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_10_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_cut_12_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake12_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake13_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake9_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake16_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake18_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake7_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake8_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake1_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake14_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake17_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake15_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake6_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake11_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake2_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake4_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake10_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake5_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chili_flake3_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ham_3_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ham_1_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ham_2_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Onion_tower_food_0.geometry}
        material={materials.food}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tiny_bowl_Added_props_0.geometry}
        material={materials.Added_props}
      />
    </group>
  )
}

useGLTF.preload('/ramen.glb')